accounts/passwords/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('password/change/', auth_views.PasswordChangeView.as_view() ,name='change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view() ,name='password_change_done'),
    path('password/reset/', auth_views.PasswordResetView.as_view() ,name='password_reset'),
    re_path(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view() ,name='password_reset_confirm'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view() ,name='password_reset_done'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view() ,name='password_reset_complete'),

]

#
# accounts[name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

accounts/urls.py
from django.urls import path, re_path
from .views import (AccountHomeView,
                    AccountEmailActivateView,
                    UserDetailUpdateView,
                    )
from products.views import ProductViewHistory

app_name = "account"
urlpatterns = [
    path('', AccountHomeView.as_view() ,name='home'),
    re_path(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view() ,name='email-activate'),
    path('email/reactivate/', AccountEmailActivateView.as_view() ,name='email-reactivate'),
    path('user/update/', UserDetailUpdateView.as_view() ,name='user-update'),
    path('products/viewed/', ProductViewHistory.as_view() ,name='products-viewed'),

]

carts/urls.py
from django.urls import path
from carts.views import cart_page, cart_update, check_out, success,entry_update

app_name="cart"
urlpatterns = [
    path('', entry_update, name="entry"),
    path('update/', cart_update, name="update"),
    path('checkout/', check_out, name="checkout"),
    path('success/', success, name="success"),
    path('entry/', cart_page, name="home"),
 ]

eflooring/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from addresses.views import addess_create, address_choose, AddressListView, AddressCreateView, AddressUpdateView
from accounts.views import LoginView, RegisterView, GuestRegisterView
from .views import home_page, contact_page, about_page
from carts.views import cart_refresh
from addresses.views import addess_create, address_choose
from accounts.views import LoginView, RegisterView, GuestRegisterView
from products.views import ProductListView,ProductDetailView
from billing.views import payment_card, payment_card_create, payment_choose, payment_method_change
from marketing.views import subscribe, MarketingPreferenceView, MailchimpWebhooView
from orders.views import OrderListView
from analytics.views import SalesView, SalesAjaxView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('about/',about_page, name='about'),
    path('contact/',contact_page, name='contact'),
    ##accounts app
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('guest/', GuestRegisterView.as_view(), name='guest_register'),

    ##retailers
    path('retailers/', include('retailers.urls', namespace='retailers')),
    ##accounts app
    path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('accounts/', include("accounts.passwords.urls")),

    ##carts app
    path('cart/', include('carts.urls', namespace='cart')),
    ##products app
    path('products/', include('products.urls', namespace='products')),
    ## search app
    path('search/', include('search.urls', namespace='search')),
    ## address
    path('accounts/address', addess_create, name='address'),
    path('accounts/address_choose', address_choose, name='address_choose'),
    path('api/cart/', cart_refresh, name='cart_refresh'),
    re_path(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    re_path(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    re_path(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    ##billing
    path('payment-card/',payment_card, name='payment_card'),
    path('payment-card-create/',payment_card_create, name='payment_card_create'),
    re_path(r'^choose-payment-method/$', payment_choose, name='payment_choose'),
    re_path(r'^change-payment-method/$', payment_method_change, name='payment_method_change'),


    ##marketing
    path('subscribe/',subscribe, name='subscribe'),
    path('subscription/',MarketingPreferenceView.as_view(), name='subscription'),
    path('webhooks/email/',MailchimpWebhooView.as_view(), name='mailchimpwebhook'),
    path('analytics/sales/',SalesView.as_view(), name='sales-report'),
    path('analytics/sales/data/', SalesAjaxView.as_view(), name='sales-analytics-data'),

    ##orders
    path('orders/', include('orders.urls', namespace='orders')),

 ]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, re_path
from .views import OrderListView, OrderDetailView

app_name = "orders"
urlpatterns = [
	path('list/', OrderListView.as_view() ,name='list'),
	re_path(r'^detail/(?P<id>[0-9A-Za-z]+)/$', OrderDetailView.as_view() ,name='detail'),
]

retailers/urls.py
from django.urls import path, re_path
from . import views


app_name="retailers"

urlpatterns = [
    re_path(r'^$', views.RetailerListView.as_view(), name="list"),
    re_path(r'^create/$', views.create_retailer, name="create"),
    re_path(r'^edit_retailer/(?P<retailer_pk>\d+)/$', views.edit_retailer, name='edit_retailer'),
    re_path(r'^api/$', views.RemoveRetailer, name='api'),
    path('map/', views.RetailerMap, name='map'),
    path('RetailerMapAjax/', views.RetailerMapAjax, name='RetailerMapAjax')

    # re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),

 ]

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.views.generic import CreateView,FormView,DetailView, ListView, UpdateView,View
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import FormMixin
from eflooring.mixins import NextUrlMixin, RequestFormAttachMixin
from .forms import LoginForm, RegisterForm, GuestForm, ReactivateEmailForm, UserDetailChangeForm
from carts.models import Cart
from .models import GuestEmail
from .signals import user_logged_in
from .models import EmailActivation





class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")

class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("login")
            else:
                  if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login")
        context = {'form': self.get_form(),'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key }
        return render(self.request, 'registration/activation-error.html', context)


class GuestRegisterView(NextUrlMixin,RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/register/'
    template_name = 'carts/checkout.html'

    def get_success_url(self):
        return self.get_next_url()
   ## requset has been send to modelForm,form valid can be moved to save() as well
    def form_valid(self, form):
        self.object=form.save(commit=True)
        request=self.request
        email = form.cleaned_data.get("email")
        request.session['guest_email_id'] = email
        return super().form_valid(form)

    def form_invalid(self, form):
        return redirect(self.default_next)

@login_required
def account_home_view(request): #accounts/login/?next=/some/path
    return render(request, "home.html", {})


class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name='accounts/home.html'

    def get_object(self):
        return self.request.user
#
# class LoginRequiredMixin(object):
#     @method_decorator(login_required)
#     def dispatch(self, *args, **kwargs):
#         return super(LoginRequiredMixin, self).dispatch(self, *args, **kwargs)

# def guest_register(request):
#     form = GuestForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#
#     if form.is_valid():
#         email = form.cleaned_data.get("email")
#         new_guest_email = GuestEmail.objects.get_or_create(email=email)
#         request.session['guest_email_id'] = email
#         if is_safe_url(redirect_path, request.get_host()):
#             return redirect(redirect_path)
#         else:
#             redirect("/register/")
#     return redirect("/register/")




class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next="/account/"

    def form_valid(self, form):
        request =self.request
        user = form.user
        print(user)
        user_logged_in.send(user.__class__, instance=user, request=request)
        ## retrive the cart and cart items number
        try:
            del request.session['guest_email_id']
        except KeyError:
            pass
        Cart.objects.load_cart(request)
        next_path= self.get_next_url()
        return redirect(next_path)



class RegisterView(SuccessMessageMixin,CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'
    success_message ='Activation link has been sent to you email, please check'
    # success_message = 'Please check your email and active you account'


# def login(request):
#     form = LoginForm(request.POST or None)
#     context = {
#         "form": form
#     }
#
#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#
#     if form.is_valid():
#         username = form.cleaned_data.get("username")
#         password = form.cleaned_data.get("password")
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             auth_login(request, user)
#             ## retrive the cart and cart items number
#             try:
#                 del request.session['guest_email_id']
#             except KeyError:
#                 pass
#
#             Cart.objects.load_cart(request)
#             if is_safe_url(redirect_path, request.get_host()):
#                 return redirect(redirect_path)
#             else:
#                 return redirect("/")
#         else:
#             print("Error")
#     return render(request, "login.html", context)
# # def register(request):
#     form = RegisterForm(request.POST or None)
#     context = {
#         "form": form
#     }
#
#     if form.is_valid():
#         print(form.cleaned_data)
#         email = form.cleaned_data.get("email")
#         password = form.cleaned_data.get("password")
#
#         new_user = User.objects.create_user(email, password)
#         print(new_user)
#     return render(request, "register.html", context)

accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <label for='email'>Email</label>
  <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
  <button type='submit' class='btn btn-default my-3'>Save</button>
  <a href='{% url "change" %}'>Change Password</a>
</form>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
<div class='col-12'>
<h1>Account</h1>
<hr/>
</div>
<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Support</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "about" %}'>About</a>
                <a class='list-group-item' href='{% url "contact" %}'>Contact</a>
            </div>
      </div>
    </div>
</div>



<div class='col-12 col-md-3 my-3' id='billing'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Billing</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "orders:list" %}'>Orders</a>
                <a class='list-group-item' href='{% url "payment_card" %}'>Update Card</a>
                <a class='list-group-item' href='{% url "addresses" %}'>Addresses</a>


            </div>
      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Account Details</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "account:user-update" %}'>Update Details</a>
                <a class='list-group-item' href='{% url "change" %}'>Change Password</a>

            </div>

      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Preferences</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "subscription" %}'>Email Marketing</a>

            </div>

      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">History</h4>
              <div class='list-group'>
                <a class='list-group-item' href='{% url "account:products-viewed" %}'>Products</a>
            </div>
      </div>
    </div>
</div>

{% if request.user.is_staff %}
<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Dashboard</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "sales-report" %}'>Sales Report</a>
                <a class='list-group-item' href='#'>Map Distribution</a>

            </div>

      </div>
    </div>
</div>
<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Retailers</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "retailers:list" %}'>Ratailer List</a>
                <a class='list-group-item' href='{% url "retailers:create" %}'>Create New</a>
                <a class='list-group-item' href='{% url "retailers:map" %}'>Map Distribution</a>

            </div>

      </div>
    </div>
</div>
{% endif %}


</div>


{% endblock %}

{#  Manage your orders: check all orders, first few orders#}
{# Personal infor & privacy: password reset, biling address, shipping address subscription#}
{#  Product viewed #}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<div class="row">
		<div class="col">
		    <h1>Login</h1>
		    <form method='POST'>
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="btn btn-default">Login</button>
			</form>
		</div
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-4 col-lg-6 col-sm-12 mx-auto">
		    <h1>Register</h1>
		    <form method='POST'>
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="btn btn-default">Register</button>
			</form>

		</div>
    </div>
{% endblock %}