carts/urls.py
from django.urls import path
from carts.views import cart_page, cart_update, check_out, success,entry_update

app_name="cart"
urlpatterns = [
    path('', entry_update, name="entry"),
    path('update/', cart_update, name="update"),
    path('checkout/', check_out, name="checkout"),
    path('success/', success, name="success"),
    path('entry/', cart_page, name="home"),
 ]

addresses/models.py
from django.db import models
from billing.models import BillingProfile
from django.urls import reverse

ADDRESS_TYPE = (
	('shipping', 'Shipping'),
	('billing', 'Billing')
	)


class Address(models.Model):
	billing_profile = models.ForeignKey(BillingProfile, on_delete=models.CASCADE)
	address_type	= models.CharField(max_length=120, choices=ADDRESS_TYPE)
	address_line1	= models.CharField(max_length=120)
	address_line2	= models.CharField(max_length=120, null=True, blank=True)
	suburb			= models.CharField(max_length=120)
	state			= models.CharField(max_length=120)
	country			= models.CharField(max_length=120, default='Australia')
	postcode	    = models.CharField(max_length=120)


	def __str__(self):
		return str(self.billing_profile)

	def get_absolute_url(self):
		return reverse("address-update", kwargs={"pk": self.pk})

	def get_address(self):
		return '{address_line1} {address_line2} {suburb} {state} {country} {postcode}'.format(
				address_line1 = self.address_line1,
				address_line2 = self.address_line2,
				suburb		  = self.suburb,
				state		  = self.state,
				country       = self.country,
				postcode	  = self.postcode

			)

addresses/forms.py
from django.forms import ModelForm
from .models import Address


class AddressForm(ModelForm):
    class Meta:
        model = Address
        exclude=['billing_profile', 'address_type']

    def __init__(self, *args, **kwargs):
        super(AddressForm, self).__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'

addresses/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView, ListView, CreateView

from django.shortcuts import render, redirect
from .forms import AddressForm
from django.utils.http import is_safe_url
from billing.models import BillingProfile
from .models import Address


class AddressListView(LoginRequiredMixin, ListView):
    template_name = 'addresses/list.html'

    def get_queryset(self):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        return Address.objects.filter(billing_profile=billing_profile)

class AddressCreateView(LoginRequiredMixin, CreateView):
    template_name = 'addresses/update.html'
    form_class = AddressForm
    success_url = '/addresses'

    def form_valid(self, form):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        instance = form.save(commit=False)
        instance.billing_profile = billing_profile
        instance.save()
        return super(AddressCreateView, self).form_valid(form)

class AddressUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'addresses/update.html'
    form_class = AddressForm
    success_url = '/addresses'
    initial={'address_line1': '13, Olver Street', 'address_line2': None, 'suburb': 'Preston', 'state': 'Victoria', 'country': 'Australia', 'postcode': '3072'}


    def get_queryset(self):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        return Address.objects.filter(billing_profile=billing_profile)

def addess_create(request):
	form = AddressForm(request.POST or None)
	next_ = request.GET.get('next')
	next_post = request.POST.get('next')
	redirect_path = next_ or next_post or None

	if form.is_valid():
		instance = form.save(commit=False)
		billing_profile, new_billing_profile = BillingProfile.objects.new_or_get(request)
		address_type = request.POST.get('address_type', 'shipping')
		instance.billing_profile = billing_profile
		instance.address_type = address_type
		instance.save()
		request.session['{}_address_id'.format(address_type)] = instance.id
		if is_safe_url(redirect_path, request.get_host()):
				return redirect(redirect_path)
				print(redirect_path)
		else:
			redirect("carts:checkout")
	return redirect("carts:checkout")


def address_choose(request):
	if request.user.is_authenticated:
		next_ = request.GET.get('next')
		next_post = request.POST.get('next')
		redirect_path = next_ or next_post or None

		if request.method == "POST":
			address_id		= request.POST.get('address', None)
			address_type 	= request.POST.get('address_type', 'shipping')
			billing_profile, new_billing_profile = BillingProfile.objects.new_or_get(request)

			if address_id is not None:
				qs = Address.objects.filter(billing_profile=billing_profile, id=address_id)
				if qs.exists():
					request.session[address_type+"_address_id"] = address_id

			if is_safe_url(redirect_path, request.get_host()):
					return redirect(redirect_path)
			else:
				redirect("carts:checkout")
		return redirect("carts:checkout")

addresses/templates/addresses/address_reuse.html
<form action='{% url "address_choose" %}' method="POST">
		{% csrf_token %}
		{% if next_url %}
		<input type='hidden' name='next' value='{{ next_url }}' />
		{% endif %}
		<input type='hidden' name='address_type' value='{{ address_type }}' />
		{% for address in address_qs %}
				<div class="form-check">
				  <input class="form-check-input" type="radio" name="address" id="address_{{ address.id }}" value="{{ address.id }}" checked>
				  <label class="form-check-label" for="address_{{ address.id }}">
				     {{ address.address_line1 }}
				  </label>
				</div>
		{% endfor %}
		<div class="my-4">
			<button class="btn btn-default"  type="submit" >Confirm</button>
		</div>
</form>

addresses/templates/addresses/form.html
<form method='POST' action='{% url "address" %}'>
	<div class="form-group">
		{% csrf_token %}
		{% if next_url %}
		<input type='hidden' name='next' value='{{ next_url }}' />
		{% endif %}
		<input type='hidden' name='address_type' value='{{ address_type }}' />
	   {{ form.as_p }}
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>

addresses/templates/addresses/list.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
<div class='col-12'>
<h1>Address{% if object_list.count > 1%}es{% endif %} <small><a href='{% url "address-create" %}'>Create New</a></small></h1>
<hr/>
</div>
</div>
<div class='row'>
        {% for obj in object_list %}
            <div class='col-12 col-md-3 my-3'>
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">{{ obj }}</h4>
                     <small>{{ obj.get_address_type_display }}</small><br/>
                     <br/>
                     <h5>Address</h5>
                     {{ obj.get_address|linebreaks }}

                    <a href='{{ obj.get_absolute_url }}' class='btn btn-default'>Edit</a>
                  </div>
                </div>
            </div>
        {% empty %}
         <p class='lead text-center'><a href='{% url "address-create" %}'>Create New</a></p>
        {% endfor %}
</div>
{% endblock %}

addresses/templates/addresses/update.html
{% extends "base.html" %}

{% block content %}

<div class='row'>
    <div class='col-10 mx-auto col-md-6 '>
        {% if form.instance.address_line1  %}
        <h3 class='my-5'>Update Address</h3>
        {% else %}
        <h3 class='my-5'>Create Address</h3>
        {% endif %}
        <hr>
    <form method='POST' action=''> {% csrf_token %}
        {{ form.as_p }}
      <button type='submit' class='btn btn-default my-3'>Save Address</button>
    </form>
    </div>

</div>

{% endblock %}