carts/urls.py
from django.urls import path
from carts.views import cart_page, cart_update, check_out, success,entry_update

app_name="cart"
urlpatterns = [
    path('', entry_update, name="entry"),
    path('update/', cart_update, name="update"),
    path('checkout/', check_out, name="checkout"),
    path('success/', success, name="success"),
    path('entry/', cart_page, name="home"),
 ]

search/urls.py
from django.urls import path
from .views import SearchProductView

app_name="search"
urlpatterns = [
    path('', SearchProductView.as_view(), name="query"),


 ]

search/views.py
from django.db.models import Q
from django.views.generic import ListView 
from django.shortcuts import render, get_object_or_404
from products.models import Product


class SearchProductView(ListView):
	template_name = "search/view.html"

	# def get_context_data(self, *args, **kwargs):
	# 	context = super().get_context_data(*args, **kwargs)
	# 	query = self.request.GET.get('q')
	# 	context['query'] = query
	# 	#SearchQuery.objects.create(query=query)
	# 	return context
	def get_queryset(self, *args, **kwargs):
		request = self.request
		method_dic = request.GET 
		print(method_dic)
		query = method_dic.get('q', None) #or method_dic['q']
		print(query)
		if query is not None:
			return Product.objects.search(query) 
		return Product.objects.featured()

search/templates/search/snippets/search_form.html
 <form method="GET" action="{% url 'search:query' %}" class="form-inline search-form">
 	<div class="input-group">
      <input class="form-control" type="search" placeholder="Search" name="q" value='{{ request.GET.q }}' aria-label="Search">
      <span class="input-group-append">
      <button class="btn btn-outline-success" type="submit">Search</button
  </span>
</div>
  </form>