carts/urls.py
from django.urls import path
from carts.views import cart_page, cart_update, check_out, success,entry_update

app_name="cart"
urlpatterns = [
    path('', entry_update, name="entry"),
    path('update/', cart_update, name="update"),
    path('checkout/', check_out, name="checkout"),
    path('success/', success, name="success"),
    path('entry/', cart_page, name="home"),
 ]

retailers/urls.py
from django.urls import path, re_path
from . import views


app_name="retailers"

urlpatterns = [
    re_path(r'^$', views.RetailerListView.as_view(), name="list"),
    re_path(r'^create/$', views.create_retailer, name="create"),
    re_path(r'^edit_retailer/(?P<retailer_pk>\d+)/$', views.edit_retailer, name='edit_retailer'),
    re_path(r'^api/$', views.RemoveRetailer, name='api'),
    path('map/', views.RetailerMap, name='map'),
    path('RetailerMapAjax/', views.RetailerMapAjax, name='RetailerMapAjax')

    # re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),

 ]

retailers/models.py
from django.db import models
from eflooring.utils import unique_slug_generator
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from django.core.validators import RegexValidator
import random
import os
from datetime import date


User = settings.AUTH_USER_MODEL

def get_filename_ext(filename):
    base_name = os.path.basename(filename)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    file_rand = random.randint(1, 1000000000)
    name, ext = get_filename_ext(filename)
    foldername = date.today().strftime('%Y%b%d')
    full_filename = 'samples/{foldername}/{name}_{file_rand}.{ext}'.format(
        foldername=foldername,
        name=name,
        file_rand=file_rand,
        ext=ext
        )
    return full_filename

class Sample(models.Model):
    title           = models.CharField(max_length=120)
    slug            =models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2,max_digits=11, default=0)
    image           = models.ImageField(upload_to=upload_image_path,null=True,blank=True)
    featured        = models.BooleanField(default=False)
    active          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)


def sample_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(sample_pre_save_receiver, sender=Sample)


class Retailer(models.Model):
    user            = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    email           = models.EmailField(verbose_name='email address',max_length=255)
    sample          = models.ManyToManyField(Sample, through='SampleBridge', blank=True)
    business_name   = models.CharField(max_length=255, blank=True, null=True)
    latitude        = models.DecimalField(decimal_places=15,max_digits=20, default=0)
    longitude       = models.DecimalField(decimal_places=15,max_digits=20, default=0)
    first_name      = models.CharField(verbose_name='first name', max_length=30, blank=True)
    last_name       = models.CharField(verbose_name='last name', max_length=30, blank=True)
    phone_regex     = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number    = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    is_active   = models.BooleanField(default=True)

    def __str__(self):
        return str(self.business_name)


class SampleBridge(models.Model):
    sample		= models.ForeignKey(Sample, on_delete=models.CASCADE)
    retailer    = models.ForeignKey(Retailer, on_delete=models.CASCADE)
    number      = models.IntegerField(default=1)
    updated		= models.DateTimeField(auto_now=True)
    timestamp	= models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     unique_together = (("sample", "retailer"),)

    def __str__(self):
        return str(self.sample)

retailers/forms.py
from django import forms
from .models import Retailer, SampleBridge,Sample
from eflooring.utils import UniqueFieldFormSet



class RetailerForm(forms.ModelForm):
    class Meta:
        model = Retailer
        exclude = [
            'is_active',
            'sample'
        ]
    def __init__(self, *args, **kwargs):
        super(RetailerForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control input-sm'


class SampleBridgeForm(forms.ModelForm):
    class Meta:
        model = SampleBridge
        fields = [
            'sample',
            'number',
        ]
    def __init__(self, *args, **kwargs):
        super(SampleBridgeForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control input-sm'


retailerFormSet = forms.modelformset_factory(
    Retailer,
    form = RetailerForm,
    fields=('business_name', 'phone_number','email'),
    extra=0,
    can_delete=True,
)



SampleBridgeFormSet = forms.modelformset_factory(
    SampleBridge,
    form = SampleBridgeForm,
    formset=UniqueFieldFormSet,#default BaseModelFormSet
    fields=('sample', 'number'),
    extra=2,
)


SampleBridgeInlineFormSet = forms.inlineformset_factory(
    Retailer,
    SampleBridge,
    formset=SampleBridgeFormSet,
    fields=('sample', 'number'),
    min_num=1,
    extra=2,

)

retailers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.http import JsonResponse
from django.views.generic import ListView
from . import forms
from . import models


@staff_member_required
def RetailerMap(request):
    return render(request, "retailers/map.html", {})

@staff_member_required
def RetailerMapAjax(request):
    # data = {}
    # if request.is_ajax():
    retailers = models.Retailer.objects.all()
    data = {
        "business":[{
            "location":[x.latitude, x.longitude],
            "name":x.business_name,
            "count":x.samplebridge_set.count(),
            "samples":[i.sample.title for i in x.samplebridge_set.all()],
            } for x in retailers]
    }
    return JsonResponse(data)

class RetailerListView(ListView):
    model = models.Retailer
    template_name = "retailers/retailer_list.html"
    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if not user.is_staff:
            return render(request, "400.html", {})
        return super(RetailerListView, self).dispatch(request,*args, **kwargs)

def RemoveRetailer(request):
    if request.method == 'POST':
        i=0
        for item in request.POST:
            print(item)
            if request.POST.get(item) and i is not 0:
                retailer = models.Retailer.objects.filter(pk=item)
                if retailer.exists():
                    retailer.first().delete()
            i+=1
    return redirect("retailers:list")


@staff_member_required
def create_retailer(request):
    form_class = forms.RetailerForm
    sample_forms = forms.SampleBridgeFormSet(
        queryset = models.SampleBridge.objects.none()
    )
    form = form_class()
    if request.method == 'POST':
        form = form_class(request.POST)
        sample_forms = forms.SampleBridgeFormSet(
            request.POST,
            queryset = models.SampleBridge.objects.none()
        )

    if form.is_valid() and sample_forms.is_valid():
        retailer = form.save()
        samples = sample_forms.save(commit=False)
        for sample in samples:
            sample.retailer = retailer
            sample.save()
            messages.success(request, "Added Retailer")
            return redirect("retailers:list")
    return render(request, 'retailers/retailer_form.html', {
        'form': form,
        'formset':sample_forms
        })


@staff_member_required
def create_retailer(request):
    form_class = forms.RetailerForm
    sample_forms = forms.SampleBridgeInlineFormSet(
        queryset = models.SampleBridge.objects.none(),
        request=request,
    )
    form = form_class()
    if request.method == 'POST':
        form = form_class(request.POST)
        sample_forms = forms.SampleBridgeInlineFormSet(
            request.POST,
            request=request,
            queryset = models.SampleBridge.objects.none(),
            field_value='sample',

        )

    if form.is_valid() and sample_forms.is_valid():
        retailer = form.save()
        samples = sample_forms.save(commit=False)
        for sample in samples:
            sample.retailer = retailer
            sample.save()
            messages.success(request, "Added Retailer")
            return redirect("retailers:list")
    return render(request, 'retailers/retailer_form.html', {
        'form': form,
        'formset':sample_forms
        })

@staff_member_required
def edit_retailer(request, retailer_pk):
    retailer = get_object_or_404(models.Retailer, pk=retailer_pk)
    form_class = forms.RetailerForm
    form = form_class(instance=retailer)
    queryset = form.instance.samplebridge_set.all()
    sample_forms = forms.SampleBridgeInlineFormSet(
        queryset = queryset,

    )

    if request.method == 'POST':
        form = form_class(request.POST, instance=retailer)
        sample_forms = forms.SampleBridgeInlineFormSet(
            request.POST,
            request=request,#  pass request to form clean method
            queryset =queryset,
            field_value='sample',
        )

    if form.is_valid() and sample_forms.is_valid():
        form.save()
        samples = sample_forms.save(commit=False)
        for sample in samples:
            sample.retailer = retailer
            sample.save()
        for sample in sample_forms.deleted_objects:
            sample.delete()
        messages.success(request, "Retailder modified")
        return redirect("retailers:list")
    return render(request, 'retailers/retailer_form.html', {
        'form': form,
        'formset':sample_forms,
        })

retailers/templates/retailers/map.html
{% extends "base.html" %}
{% load static %}

{% block title %}map{% endblock%}
{% block css %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.3/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>

{% endblock %}
{% block js %}
<script src="https://unpkg.com/leaflet@1.3.3/dist/leaflet.js" integrity="sha512-tAGcCfR4Sc5ZP5ZoVz0quoZDYX5aCtEm/eu1KhSLj2c9eFrylXZknQYmxUssFaVJKvvc0dJQixhGjG2yXWiV9Q==" crossorigin=""></script>
<script>
$(document).ready(function(){
    var url='/retailers/RetailerMapAjax/';
    var method='GET';
    $.ajax({
        url:url,
        method:method,
        success: function(responseData){
            console.log(responseData.business[0]['location']);
            const business = responseData.business;
            renderMap(business)
        },
        errer: function(error){
            $.alert("An error occured")
        }
    })
});
const greeni = '{% static "retailers/img/marker-green.png" %}'
const redi = '{% static "retailers/img/marker-red.png" %}'
const yellowi = '{% static "retailers/img/marker-yellow.png" %}'
const s = '{% static "retailers/img/marker-shadow.png" %}'

const renderMap = (business) => {
    const greenIcon = L.icon({
        iconUrl: greeni,
        shadowUrl: s,
        iconSize:     [38, 95], // size of the icon
        shadowSize:   [50, 64], // size of the shadow
        iconAnchor:   [22, 94], // point of the icon which will correspond to marker's location
        shadowAnchor: [4, 62],  // the same for the shadow
        popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
    });
    const redIcon = L.icon({
        iconUrl: redi,
        shadowUrl: s,
        iconSize:     [38, 95], // size of the icon
        shadowSize:   [50, 64], // size of the shadow
        iconAnchor:   [22, 94], // point of the icon which will correspond to marker's location
        shadowAnchor: [4, 62],  // the same for the shadow
        popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
    });
    const yellowIcon = L.icon({
        iconUrl: yellowi,
        shadowUrl: s,
        iconSize:     [38, 95], // size of the icon
        shadowSize:   [50, 64], // size of the shadow
        iconAnchor:   [22, 94], // point of the icon which will correspond to marker's location
        shadowAnchor: [4, 62],  // the same for the shadow
        popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
    });

    const grayscaleUrl = 'http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png';
    const streetsUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    const list = [];
    let markerIcon ='';
    for (i=0; i < business.length; i++) {
        const location = business[i]['location'];
        const name = business[i]['name'];
        const count = business[i]['count'];
        const samples = business[i]['samples'];
        if (count >= 31){
            markerIcon = greenIcon;
        } else if (count<31&&count>=15){
            markerIcon = redIcon
        } else{
            markerIcon = yellowIcon
        }
        let marker = L.marker(location, {icon:markerIcon})
                      .bindPopup('<h4>'+name+'</h4>'+''+'No.: '+count+'<br />'+'Samples: '+samples.join(' | '))
        list.push(marker)

    }
    // var tfc = L.marker([-37.746243, 145.0041753]).bindPopup('This is GD flooring');
    // var gfc = L.marker(location).bindPopup('This is Goldenfield, CO.'+location);

    var Melbourne = L.layerGroup(list);

    var grayscale = L.tileLayer(grayscaleUrl, {id: 'MapID'}),
        streets   = L.tileLayer(streetsUrl, {id: 'MapID'});



    var mymap = L.map('mapid', {
        center: [-37.8136, 144.9631],
        zoom: 10,
        layers: [grayscale, Melbourne],
        attributionControl: false,
    });
    $(".nav-link").click(function(e) {
        $(".active").removeClass("active");
        $(this).addClass("active");
        var pos = e.target.getAttribute('data-position');
        var zoom = e.target.getAttribute('data-zoom');
        if (pos && zoom) {
            var loc = pos.split(',');
            var z = parseInt(zoom);
            mymap.setView(loc, z, {animation: true});
            return false;
        }
    });


    var baseMaps = {
        "<span style='color: gray'>Grayscale</span>": grayscale,
        "Streets": streets
    };
    //
    var overlayMaps = {
        "Cities": Melbourne
    };

    L.control.layers(baseMaps, overlayMaps).addTo(mymap);

}



 // var mymap = L.map('mapid').setView([-37.8136, 144.9631], 10);
 // L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png').addTo(mymap);
// var tfc = L.marker([-37.746243, 145.0041753]).addTo(mymap).bindPopup('This is GD Flooring');
// var gfc = L.marker([-37.7167725, 144.9826217]).addTo(mymap).bindPopup('This is Goldenfield');


 </script>
{% endblock %}

{% block map %}
<div id="map" class="my-4 mx">
<ul class="nav nav-pills">
      <li class="nav-item">
        <a href="#" class="nav-link active" data-zoom="10" data-position="-37.8136, 144.9631">
            Melbourne
        </a>
      </li>
       <li class="nav-item">
        <a href="#" class="nav-link" data-zoom="10" data-position="-33.8688,151.2093">
            Sydney
        </a>
     </li>
</ul>


</div>
<div class="my-1 mx" id="mapid" style="height:680px;"></div>
{% endblock %}

retailers/templates/retailers/remove_form.html
	<input type='checkbox' name='{{ retailer_pk }}'/>

retailers/templates/retailers/retailer_form.html
{% extends "base.html" %}
{% block title %}
    {{ form.instance.business_name|default:"Create a new retailer" }}
{% endblock %}
{% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"></script>
  <script>
      $('.sample-form').formset({
          addText: 'add answer',
          deleteText: 'remove'
      });
  </script>

{% endblock %}

{% block content %}
	<div class='container'>
        <h1> {{ form.instance.business_name|default:"Create a new Business"}}</h1>
        <form method="POST" action="">
        {% csrf_token %}
         {% for field in form %}
         <div class="form-group">
             {{ field.label }}
             {{ field }}
         </div>

         {% endfor %}
        {{ formset.management_form }}

        <table role="grid" class="stack hover" style="width: 100%">
            <thead>
                <tr>
                    <th scope="col" class="text-center" style="width: 10%">Sample</th>
                    <th scope="col" class="text-center">Number</th>
                    <th scope="col" class="text-center" style="width: 10%">Delete?</th>
                </tr>
            </thead>
            <tbody class="order">
                {% for form in formset %}
                {{ form.id }}
                <div class="{{ form.prefix }}">
                    <tr class="sample-form {% if form.instance.pk %}item{% else %}new{% endif %}">
                        <td scope="col" class="text-center">{{ form.sample }}</td>
                        <td scope="col" class="text-center">{{ form.number }}</td>
                        {% if form.instance.pk %}
                            <td class="text-center">{{ form.DELETE }}</td>
                        {% else %}
                            <td class="text-center"></td>
                        {% endif %}
                    </tr>
             </div>
                {% endfor %}
            </tbody>
        </table>

        <input type="submit" class="button btn btn-primary my-5" value="Submit">
    </form>
	</div>






{% endblock %}

retailers/templates/retailers/retailer_list.html
{% extends "base.html" %}
{% block title %}
retailers
{% endblock%}
{% block js %}

{% endblock %}
{% block content %}
	<div class='container'>

			<div class='mx-auto py-3'>
                <form method='POST', action='{% url "retailers:api" %}'>
                    {% csrf_token %}
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Company</th>
                      <th scope="col">Phone</th>
                      <th scope="col">Email</th>
                      <th scope="col">Sample#</th>
                      <th scope="col">Delete?</th>


                    </tr>
                  </thead>
                  <tbody>
                   {% for obj in object_list %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>
                          <a href="{% url 'retailers:edit_retailer' retailer_pk=obj.pk %}">
                              {{ obj.business_name }}
                          </a>
                      </td>
                      <td>{{ obj.phone_number }}</td>
                      <td>{{ obj.email }}</td>
                      <td>{{ obj.samplebridge_set.count }}</td>
                      <td>
                         {% include 'retailers/remove_form.html' with retailer_pk=obj.pk  %}
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                <input type="submit" class="btn btn-default" value="Submit"/>
                <a href='{% url "retailers:create" %}'>Create New</a>
            </form>
			</div>

		</div>

	</div>




{% endblock %}